# Generated by Django 3.2.25 on 2026-01-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
