# Generated by Django 3.2.25 on 2026-01-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0002_alter_rating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': '3. Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': '5. Города'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': '6. Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': '4. Оценки'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-departure_datetime'], 'verbose_name': 'Поездка', 'verbose_name_plural': '2. Поездки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '1. Пользователи'},
        ),
    ]
