# Generated by Django 3.2.25 on 2026-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер'),
        ),
    ]
