# Generated by Django 5.2.9 on 2026-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0005_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-population', 'name'], 'verbose_name': 'Город', 'verbose_name_plural': '5. Города'},
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(default='RU', help_text='ISO код страны', max_length=2),
        ),
        migrations.AddField(
            model_name='city',
            name='geoname_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(db_index=True, default='Россия', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(db_index=True, help_text='Область/Регион', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'region', 'country'), name='unique_city_region_country'),
        ),
    ]
