# Generated by Django 5.2.9 on 2026-01-18 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0009_trip_status_departure_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(db_index=True, default='Россия', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_code',
            field=models.CharField(default='RU', max_length=2, verbose_name='ISO код страны'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный город'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Население'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Область/Регион'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Доступно мест'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Всего мест'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аватар (URL)'),
        ),
    ]
