# Generated by Django 6.0.1 on 2026-02-11 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0015_add_car_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': '8. Группы'},
        ),
        migrations.RenameIndex(
            model_name='carcatalog',
            new_name='carpooling__make_a4fcb2_idx',
            old_name='carpooling_c_make_7c0b0d_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_invite_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_new', 'Новое бронирование'), ('booking_confirmed', 'Бронирование подтверждено'), ('booking_rejected', 'Бронирование отклонено'), ('booking_cancelled', 'Бронирование отменено'), ('trip_cancelled', 'Поездка отменена'), ('trip_updated', 'Поездка обновлена'), ('leave_rating', 'Оставить отзыв')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='parcel_allowed',
            field=models.BooleanField(default=False, verbose_name='Перевозка посылок'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='smoking_allowed',
            field=models.BooleanField(default=False, verbose_name='Остановки на перекур'),
        ),
    ]
