"""
Django settings for GoGoCarpool project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Загрузка скрытых настроек из hiddensettings.env (если файл есть и установлен python-dotenv)
BASE_DIR = Path(__file__).resolve().parent.parent
_env_file = BASE_DIR / 'hiddensettings.env'
if _env_file.exists():
    try:
        from dotenv import load_dotenv
        load_dotenv(_env_file)
    except ImportError:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-g$cwk9qb1)1l&!ar^_+5cy72@4-@$jj@2*+0nw054k__^@w4+4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if os.environ.get('DJANGO_ALLOWED_HOSTS') else []
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    _allowed = [*_allowed, _render_host, '.onrender.com']
ALLOWED_HOSTS = [h.strip() for h in _allowed if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    'carpooling.apps.CarpoolingConfig',
]

# Кастомная модель пользователя
AUTH_USER_MODEL = 'carpooling.User'

# добавлены рест, трипс

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "GoGoCarpool.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "GoGoCarpool.wsgi.application"


# Database
# DATABASE_URL — на Render подставляется автоматически при подключении PostgreSQL.
# Иначе DJANGO_DB_* из hiddensettings.env или SQLite.

if _database_url := os.environ.get("DATABASE_URL"):
    import dj_database_url
    DATABASES = {"default": dj_database_url.config(default=_database_url, conn_max_age=600)}
else:
    _db_name = os.environ.get("DJANGO_DB_NAME")
    _db_user = os.environ.get("DJANGO_DB_USER")
    _db_password = os.environ.get("DJANGO_DB_PASSWORD", "")
    if _db_name and _db_user:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": _db_name,
                "USER": _db_user,
                "PASSWORD": _db_password,
                "HOST": os.environ.get("DJANGO_DB_HOST", "127.0.0.1"),
                "PORT": os.environ.get("DJANGO_DB_PORT", "5432"),
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_L10N = False  # Отключаем локализацию для использования кастомных форматов

USE_TZ = True

# Формат даты и времени для РФ (дд.мм.гггг)
DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i'
SHORT_DATE_FORMAT = 'd.m.Y'
SHORT_DATETIME_FORMAT = 'd.m.Y H:i'
DATE_INPUT_FORMATS = [
    '%d.%m.%Y',  # 18.01.2026
    '%d.%m.%y',  # 18.01.26
    '%Y-%m-%d',  # 2026-01-18 (ISO формат для совместимости)
]
DATETIME_INPUT_FORMATS = [
    '%d.%m.%Y %H:%M',     # 18.01.2026 14:30
    '%d.%m.%Y %H:%M:%S',  # 18.01.2026 14:30:00
    '%d.%m.%y %H:%M',     # 18.01.26 14:30
    '%Y-%m-%d %H:%M',     # 2026-01-18 14:30 (ISO формат для совместимости)
    '%Y-%m-%d %H:%M:%S',  # 2026-01-18 14:30:00
]


# Email settings (Yandex SMTP)
# В разработке: EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend 
# В .env письма выводятся в терминал Django вместо отправки.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.yandex.ru')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'sabenoreplay@yandex.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'sabenoreplay@yandex.com')
SERVER_EMAIL = os.environ.get('EMAIL_HOST_USER', 'sabenoreplay@yandex.com')
# Адрес для приёма жалоб на пользователей (нигде не показывается в UI)
REPORT_EMAIL = os.environ.get('REPORT_EMAIL', 'akimo7abe@gmail.com')


# GeoNames - бесплатная база городов
# Данные импортируются командой: python manage.py import_geonames
# Документация: https://download.geonames.org/export/dump/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "frontend" / "dist"] if (BASE_DIR / "frontend" / "dist").exists() else []
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DATETIME_FORMAT": "%d.%m.%Y %H:%M",
    "DATE_FORMAT": "%d.%m.%Y",
    "DATETIME_INPUT_FORMATS": ["%d.%m.%Y %H:%M", "%d.%m.%Y %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%dT%H:%M:%SZ"],
    "DATE_INPUT_FORMATS": ["%d.%m.%Y", "%Y-%m-%d"],
}


# Celery settings (Redis)
_redis_url = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 минут максимум на задачу


# Ссылка на фронт для писем (ссылки на поездки и т.д.)
_render = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
FRONTEND_URL = (f"https://{_render}" if _render else os.environ.get('FRONTEND_URL', 'http://localhost:5173')).rstrip('/')

# CORS settings
_cors_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
if _render_host := os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    _cors_origins.append(f"https://{_render_host}")
CORS_ALLOWED_ORIGINS = _cors_origins
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [o.replace('http://', 'https://') for o in _cors_origins]

# Куки сессии и CSRF по HTTPS (Render): без Secure браузер не отправляет куки
if os.environ.get('RENDER_EXTERNAL_HOSTNAME') or not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
